language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgres
before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - python manage.py migrate
  - python manage.py makemigrations
  - python manage.py migrate
script: python manage.py test