# Generated by Django 2.0.1 on 2018-03-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libPolicyCount', models.IntegerField()),
                ('fasPolicyCount', models.IntegerField()),
                ('electionTracker', models.IntegerField()),
                ('statusID', models.IntegerField()),
                ('gameOver', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('isAlive', models.BooleanField()),
                ('president', models.BooleanField()),
                ('previousPresident', models.BooleanField()),
                ('chancellor', models.BooleanField()),
                ('previousChancellor', models.BooleanField()),
                ('party', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('vote', models.NullBooleanField()),
            ],
        ),
    ]
