# Generated by Django 2.0.1 on 2018-03-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20180306_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscardPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_AffiliationCheckOccurred1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_AffiliationCheckOccurred2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_Exection1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_Exection2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_PolicyPeekDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='EX_SpecialElectionCalled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='cardsForChancellor1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='cardsForChancellor2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='lastPolicyPassed',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='statusUpdate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
