# Generated by Django 2.0.1 on 2018-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20180307_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
                ('special', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='previousPresident',
            field=models.BooleanField(default=False),
        ),
    ]
