# Generated by Django 2.0.1 on 2018-03-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20180308_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='party',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(default='', max_length=10),
        ),
    ]
