# Generated by Django 2.0.3 on 2018-03-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20180319_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discardpile',
            name='card',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='cardsForChancellor1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='cardsForChancellor2',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='lastPolicyPassed',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='party',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='policydeck',
            name='card',
            field=models.CharField(default='', max_length=20),
        ),
    ]
